# Generated by Django 5.1.2 on 2025-01-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_perfil_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='plano',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
