# Generated by Django 3.0 on 2025-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_perfil_options_alter_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
