# Generated by Django 3.0 on 2025-02-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_alter_perfil_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
