import os
import django

# Configura o Django para usar o settings do projeto
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cinespace.settings')
django.setup()

from pesquisa.models import Midia, Genero, Ator  # Importe seus modelos

# Função para criar gêneros
def create_generos():
    generos = [
        "Ação", "Aventura", "Terror", "Comédia", "Drama", "Ficção Científica",
        "Romance", "Animação", "Documentário", "Suspense", "Fantasia", "Crime",
        "Guerra", "Musical", "Família", "Histórico", "Biografia", "Esporte",
    ]

    for nome in generos:
        Genero.objects.get_or_create(nome=nome)
    print("Gêneros criados com sucesso!")

# Função principal para popular o banco de dados
def populate_db():
    # Limpa as mídias existentes
    Midia.objects.all().delete()

    # Cria os gêneros
    create_generos()

    # Dados de exemplo para mídias
    midias = [
    {
        "titulo": "Vingadores: Ultimato",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/19/04/26/17/30/2428965.jpg",
        "url": "/filmes/vingadores-ultimato/",
        "ano": 2019,
        "classificacao": 5.9,
        "duracao": "3h 2min",
        "descricao": "Os Vingadores restantes devem encontrar uma maneira de desfazer as ações de Thanos e restaurar a ordem no universo.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
    {
        "titulo": "300: A Ascensão do Império",
        "tipo": "filme",
        "image_url": "https://m.media-amazon.com/images/S/pv-target-images/b767d2c689e72961a4fcb7d054c1b849971f96bbf2fc545158f194a8fc8b71ff.jpg",
        "url": "/filmes/300-ascensao-do-imperio/",
        "ano": 2014,
        "classificacao": 4.7,
        "duracao": "1h 42min",
        "descricao": "O general grego Themistokles lidera a luta contra a invasão persa liderada por Xerxes e Artemisia.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Guerra", "Histórico"]
    },
    {
        "titulo": "Invocação do Mal 2",
        "tipo": "filme",
        "image_url": "https://br.web.img2.acsta.net/c_310_420/pictures/16/04/18/20/43/025084.jpg",
        "url": "/filmes/invocacao-do-mal-2/",
        "ano": 2016,
        "classificacao": 5.1,
        "duracao": "2h 14min",
        "descricao": "Lorraine e Ed Warren viajam para Londres para investigar uma atividade paranormal em uma casa assombrada.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Terror", "Suspense"]
    },
    {
        "titulo": "Gladiador 2",
        "tipo": "filme",
        "image_url": "https://br.web.img2.acsta.net/img/40/27/4027cc2b52f4759c444e28c753ae0b2e.jpg",
        "url": "/filmes/gladiador-2/",
        "ano": 2024,
        "classificacao": 4.3,
        "duracao": "2h 35min",
        "descricao": "Sequência do aclamado filme Gladiador.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Ação", "Drama", "Histórico"]
    },
    {
        "titulo": "Uma Ideia de Você",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/24/03/06/17/15/1070935.jpg",
        "url": "/filmes/uma-ideia-de-voce/",
        "ano": 2024,
        "classificacao": 3.1,
        "duracao": "1h 50min",
        "descricao": "Uma mãe solteira se envolve romanticamente com o vocalista de uma popular boy band.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Romance", "Comédia"]
    },
    {
        "titulo": "Arremessando Alto",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/22/05/25/20/17/5781885.jpg",
        "url": "/filmes/arremessando-alto/",
        "ano": 2022,
        "classificacao": 5.4,
        "duracao": "2h 17min",
        "descricao": "Um olheiro de basquete decadente encontra um talento promissor nas ruas da Espanha e tenta levá-lo para a NBA.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Drama", "Esporte"]
    },
    {
        "titulo": "Corações de Ferro",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/14/10/28/21/28/104479.jpg",
        "url": "/filmes/coracoes-de-ferro/",
        "ano": 2014,
        "classificacao": 4.6,
        "duracao": "2h 14min",
        "descricao": "Em abril de 1945, uma tripulação de tanque americano luta para sobreviver atrás das linhas inimigas na Alemanha nazista.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Guerra", "Drama"]
    },
    {
        "titulo": "Vingadores: Era de Ultron",
        "tipo": "filme",
        "image_url": "https://br.web.img2.acsta.net/pictures/15/02/24/18/27/528824.jpg",
        "url": "/filmes/vingadores-era-de-ultron/",
        "ano": 2015,
        "classificacao": 5.8,
        "duracao": "2h 21min",
        "descricao": "Quando Tony Stark tenta lançar um programa de manutenção da paz dormente, as coisas dão errado e os Heróis Mais Poderosos da Terra devem impedir Ultron de promulgar seus terríveis planos.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
    {
        "titulo": "Outra Chance Para o Amor",
        "tipo": "filme",
        "image_url": "https://m.media-amazon.com/images/S/pv-target-images/50e9a5fd366711a9c9bea91ef1f85e77c6eb93fcb6f272f9a217eff8fa3d7fc4.jpg",
        "url": "/filmes/outra-chance-para-o-amor/",
        "ano": 2024,
        "classificacao": 4.1,
        "duracao": "1h 45min",
        "descricao": "Uma mulher tem uma nova chance de encontrar o amor quando conhece um homem que a lembra de seu primeiro amor.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Romance", "Drama"]
    },
    {
        "titulo": "Sonic 3: O Filme",
        "tipo": "filme",
        "image_url": "https://ingresso-a.akamaihd.net/prd/img/movie/sonic-3-o-filme/4d756249-3b88-4b59-baa2-527f5e3d4c3e.webp",
        "url": "/filmes/sonic-3-o-filme/",
        "ano": 2024,
        "classificacao": 5.7,
        "duracao": "1h 40min",
        "descricao": "Sonic e seus amigos enfrentam novas ameaças em sua terceira aventura cinematográfica.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Aventura", "Família"]
    },
    {
        "titulo": "Mufasa: O Rei Leão",
        "tipo": "filme",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/1/1a/Mufasa_P%C3%B4ster.webp",
        "url": "/filmes/mufasa-o-rei-leao/",
        "ano": 2024,
        "classificacao": 5.3,
        "duracao": "1h 55min",
        "descricao": "A história da origem de Mufasa, o pai de Simba.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Família", "Musical"]
    },
     {
        "titulo": "Deadpool & Wolverine",
        "tipo": "filme",
        "image_url": "https://m.media-amazon.com/images/S/pv-target-images/dd6fb66997dd4cb5606b587bb255d2cd2cec20ecbd11852a8f6b07a1358d09a1.jpg",
        "url": "/filmes/deadpool-wolverine/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "2h 10min",
        "descricao": "Deadpool e Wolverine se unem em uma aventura cheia de ação e humor.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Comédia", "Aventura"]
    },
    {
        "titulo": "Need for Speed - O Filme",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/14/03/08/08/41/128657.jpg",
        "url": "/filmes/need-for-speed-o-filme/",
        "ano": 2014,
        "classificacao": 4.9,
        "duracao": "2h 12min",
        "descricao": "Um piloto de rua é incriminado por um crime que não cometeu e busca vingança após sair da prisão.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Ação", "Crime", "Suspense"]
    },
    {
        "titulo": "Clube da Luta",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/medias/nmedia/18/90/95/96/20122166.jpg",
        "url": "/filmes/clube-da-luta/",
        "ano": 1999,
        "classificacao": 4.9,
        "duracao": "2h 19min",
        "descricao": "Um homem deprimido que sofre de insônia conhece um estranho vendedor de sabonetes e juntos eles criam um clube underground.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Drama", "Suspense", "Crime"]
    },
    {
        "titulo": "Gente Grande",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/210/299/21029996_20130821205722213.jpg",
        "url": "/filmes/gente-grande/",
        "ano": 2010,
        "classificacao": 5.9,
        "duracao": "1h 42m",
        "descricao": "Um grupo de amigos se reúne após anos para honrar seu falecido treinador de basquete.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Comédia", "Família"]
    },
    {
        "titulo": "Homem-Aranha: Sem Volta para Casa",
        "tipo": "filme",
        "image_url": "https://static.wikia.nocookie.net/marvel-dublagem/images/4/44/Homem-Aranha_-_Sem_Volta_Para_Casa.webp/revision/latest?cb=20220327173412&path-prefix=pt-br",
        "url": "/filmes/homem-aranha-sem-volta-para-casa/",
        "ano": 2021,
        "classificacao": 4.5,
        "duracao": "2h 28m",
        "descricao": "Peter Parker pede a ajuda do Doutor Estranho para que o mundo esqueça sua identidade secreta, mas o feitiço dá errado.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
    {
        "titulo": "Planeta dos Macacos: O Reinado",
        "tipo": "filme",
        "image_url": "https://m.media-amazon.com/images/M/MV5BYTkwMmIyNWQtNWEyZS00M2M3LTgxZGEtMDlmMGIzZGM4NWNhXkEyXkFqcGc@._V1_.jpg",
        "url": "/filmes/planeta-dos-macacos-o-reinado/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "2h 25m",
        "descricao": "Anos após o reinado de César, um jovem símio embarca em uma jornada que o fará questionar tudo que sabe sobre o passado e tomar decisões que definirão o futuro de símios e humanos.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
    {
        "titulo": "Bad Boys: Até o Fim",
        "tipo": "filme",
        "image_url": "https://cdn.ome.lt/hVwtHlWqtRtNeOC3YhMML1nx9zY=/fit-in/837x500/smart/uploads/conteudo/fotos/GK5IYwoWsAAhG9s.jpeg",
        "url": "/filmes/bad-boys-4/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 55m",
        "descricao": "Os parceiros Mike Lowrey e Marcus Burnett estão de volta para mais uma missão explosiva. Mas agora, tudo virou do avesso: eles estão sendo caçados.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Comédia", "Crime"]
    },
    {
        "titulo": "Annabelle",
        "tipo": "filme",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/9/9b/Annabelle-poster.jpg",
        "url": "/filmes/annabelle/",
        "ano": 2014,
        "classificacao": 4.9,
        "duracao": "1h 38m",
        "descricao": "John Form encontra o presente perfeito para sua esposa grávida, Mia: uma linda boneca vintage com um vestido branco. Mas o encanto de Mia por Annabelle não dura muito. Em uma noite horrível, sua casa é invadida por membros de um culto satânico, que atacam violentamente o casal. Nada do que fariam, no entanto, se compararia com a maldade invocada pela entidade: Annabelle.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Terror", "Suspense"]
    },
    {
        "titulo": "Hotel Transilvânia",
        "tipo": "filme",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/b/b8/Hotel_Transylvania.jpg",
        "url": "/filmes/hotel-transilvania/",
        "ano": 2012,
        "classificacao": 4.9,
        "duracao": "1h 31m",
        "descricao": "Drácula é o proprietário do Hotel Transilvânia, um resort cinco estrelas onde os monstros podem relaxar e se divertir em segurança, longe dos humanos. Drácula convida alguns dos monstros mais famosos para comemorar o 118º aniversário de sua filha Mavis. Mas a festa de Drácula é arruinada quando um humano chamado Jonathan chega ao hotel e se apaixona por Mavis.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Comédia", "Família"]
    },
    {
        "titulo": "Liga da Justiça de Zack Snyder",
        "tipo": "filme",
        "image_url": "https://musicart.xboxlive.com/7/d5a25100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080",
        "url": "/filmes/liga-da-justica-de-zack-snyder/",
        "ano": 2021,
        "classificacao": 4.9,
        "duracao": "4h 2m",
        "descricao": "Após o sacrifício altruísta de Superman, Bruce Wayne está determinado a garantir que o último sacrifício do herói não tenha sido em vão, então ele une forças com Diana Prince para recrutar uma equipe de metahumanos para proteger o mundo de uma ameaça catastrófica que se aproxima. A tarefa é mais difícil do que Bruce imaginava, pois cada um deve enfrentar os demônios de seus próprios passados para transcender o que os impediu, permitindo que se unissem e, finalmente, formassem uma liga de heróis sem precedentes. Agora unidos, Batman, Mulher Maravilha, Aquaman, Ciborgue e Flash devem salvar o planeta de Steppenwolf, DeSaad e Darkseid e suas terríveis intenções.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
     {
        "titulo": "Thunderbolts*",
        "tipo": "filme",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/d/da/Thunderbolts_2025.jpg",
        "url": "/filmes/thunderbolts/",
        "ano": 2025,
        "classificacao": 4.5,
        "duracao": "desconhecido",
        "descricao": "Ainda sem sinopse.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
     {
        "titulo": "Capitão América: Admirável Mundo Novo",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTvLREsZsA67x2xbv43gZfecSQxU9SUxxv18h5d5xjtNQPqEoQZ",
        "url": "/filmes/capitao-america-admiravel-mundo-novo/",
        "ano": 2025,
        "classificacao": 4.8,
        "duracao": "desconhecido",
        "descricao": "Sam Wilson assume o manto de Capitão América em uma nova aventura.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
    {
        "titulo": "Kraven, o Caçador",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTV8oe8nCv3hYp61LjZSkVXGxcWXC7GWJOa0fOSEt-OZc8XMZt-",
        "url": "/filmes/kraven-o-cacador/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "desconhecido",
        "descricao": "A história de origem do famoso vilão da Marvel, Kraven, o Caçador.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Aventura", "Suspense"]
    },
    {
        "titulo": "Blade Runner 2049",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/17/08/25/11/58/463146.jpg",
        "url": "/filmes/blade-runner-2049/",
        "ano": 2017,
        "classificacao": 4.9,
        "duracao": "2h 44m",
        "descricao": "Em uma sociedade futurista, um novo blade runner, o agente K (Ryan Gosling), desenterra um segredo há muito enterrado que tem o potencial de mergulhar o que resta da sociedade no caos. A descoberta de K o leva a uma busca por Rick Deckard (Harrison Ford), um ex-blade runner da polícia de Los Angeles que está desaparecido há 30 anos.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Ficção Científica", "Suspense", "Ação"]
    },
    {
        "titulo": "Divertida Mente 2",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfG1TPdn9qevW-M5UEv-4F1BqgWm3VdTIdR9xM7H_pwGJ-BDzt",
        "url": "/filmes/divertida-mente-2/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 36m",
        "descricao": "Alegria, Tristeza, Raiva, Medo e Nojinho têm rodado um negócio de sucesso nos últimos anos. Até que um dia, quando Riley faz 13 anos, a ansiedade chega. Baseado na adorada história da Disney e Pixar, o filme dá as boas-vindas a um conjunto de novas emoções quando os adolescentes enfrentam grandes mudanças na vida.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Comédia", "Família"]
    },
    {
        "titulo": "Meu Malvado Favorito 4",
        "tipo": "filme",
        "image_url": "https://ingresso-a.akamaihd.net/prd/img/movie/meu-malvado-favorito-4/4d756249-3b88-4b59-baa2-527f5e3d4c3e.webp",
        "url": "/filmes/meu-malvado-favorito-4/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 45m",
        "descricao": "Ainda sem sinopse.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Comédia", "Família"]
    },
    {
        "titulo": "Moana 2",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYirR94uovQIQJupt921e767nzgz9V9bdPK6_AVjkJ5HwoHFdU",
        "url": "/filmes/moana-2/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 40m",
        "descricao": "Moana embarca em uma nova jornada pelos mares do Pacífico.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Aventura", "Musical"]
    },
    {
        "titulo": "A Arte de Amar",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRpsQ-QSUCk430VuvwPWqMxE9f0sGzpSBFy1Q-c-xCALwyHKTGG",
        "url": "/filmes/a-arte-de-amar/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 48m",
        "descricao": "Uma história de amor e autodescoberta através da arte.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Romance", "Drama"]
    },
    {
        "titulo": "Imaculada",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRUIFM6KonL1c8k06kqtRbY_1CKERViw0UMjIdMy266Fha8ToAI",
        "url": "/filmes/imaculada/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 29m",
        "descricao": "A fé de uma jovem americana é colocada à prova em um remoto convento italiano, onde ela descobre segredos obscuros e horrores impensáveis.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Terror", "Suspense"]
    },
     {
        "titulo": "Gladiador",
        "tipo": "filme",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/4/44/GladiadorPoster.jpg",
        "url": "/filmes/gladiador/",
        "ano": 2000,
        "classificacao": 4.5,
        "duracao": "2h 55m",
        "descricao": "Um general romano busca vingança após ser traído e escravizado.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Ação", "Drama", "Histórico", "Guerra"]
    },
     {
        "titulo": "O Poderoso Chefão",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/medias/nmedia/18/90/93/20/20120876.jpg",
        "url": "/filmes/o-poderoso-chefao/",
        "ano": 1972,
        "classificacao": 4.8,
        "duracao": "2h 55m",
        "descricao": "Uma família mafiosa italiana luta para manter o poder e o controle em Nova York.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Crime", "Drama"]
    },
      {
        "titulo": "Eu Sou a Lenda",
        "tipo": "filme",
        "image_url": "https://s1.static.brasilescola.uol.com.br/be/conteudo/images/o-filme-eu-sou-lenda-pode-ser-usado-nas-aulas-biologia-por-abordar-temas-como-doencas-virais-imunizacao-5bcf030bce2eb.jpg",
        "url": "/filmes/eu-sou-a-lenda/",
        "ano": 2007,
        "classificacao": 4.9,
        "duracao": "1h 41m",
        "descricao": "Robert Neville, um brilhante cientista, é o único sobrevivente de uma epidemia que transformou a humanidade em monstros. Sozinho em Nova York, ele luta para encontrar uma cura e enviar uma mensagem de esperança.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Drama", "Ficção Científica", "Suspense"]
    },
      {
        "titulo": "Como Eu Era Antes de Você",
        "tipo": "filme",
        "image_url": "https://br.web.img2.acsta.net/pictures/16/02/03/19/11/303307.jpg",
        "url": "/filmes/como-eu-era-antes-de-voce/",
        "ano": 2016,
        "classificacao": 4.9,
        "duracao": "1h 50m",
        "descricao": "Uma jovem começa a trabalhar como cuidadora de um tetraplégico e, aos poucos, eles desenvolvem um forte vínculo.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Romance", "Drama"]
    },
     {
        "titulo": "A Culpa É das Estrelas",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/14/01/23/14/12/101764.jpg",
        "url": "/filmes/a-culpa-e-das-estrelas/",
        "ano": 2014,
        "classificacao": 4.9,
        "duracao": "2h 6m",
        "descricao": "Dois jovens com câncer se encontram em um grupo de apoio e iniciam uma jornada intensa de amor e autodescoberta.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Romance", "Drama"]
    },
     {
        "titulo": "Transformers",
        "tipo": "filme",
        "image_url": "https://m.media-amazon.com/images/M/MV5BZjM3ZDA2YmItMzhiMi00ZGI3LTg3ZGQtOTk3Nzk0MDY0ZDZhXkEyXkFqcGc@._V1_.jpg",
        "url": "/filmes/transformers/",
        "ano": 2007,
        "classificacao": 4.9,
        "duracao": "2h 24m",
        "descricao": "Uma antiga guerra entre robôs alienígenas chega à Terra, e um adolescente se torna a última esperança para a humanidade.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Ação", "Ficção Científica"]
    },
    {
        "titulo": "Lágrimas do Sol",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/medias/nmedia/18/91/11/52/20130187.jpg",
        "url": "/filmes/lagrimas-do-sol/",
        "ano": 2003,
        "classificacao": 4.9,
        "duracao": "2h 1m",
        "descricao": "Um oficial das forças especiais lidera uma missão perigosa para resgatar uma médica e freiras em meio a uma guerra civil na Nigéria.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Ação", "Guerra", "Drama"]
    },
         {
        "titulo": "Interestelar",
        "tipo": "filme",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/3/3a/Interstellar_Filme.png",
        "url": "/filmes/interestelar/",
        "ano": 2014,
        "classificacao": 4.9,
        "duracao": "2h 49m",
        "descricao": "Em um futuro próximo, a Terra se torna inabitável e um grupo de astronautas viaja por um buraco de minhoca em busca de um novo lar para a humanidade.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Aventura", "Drama", "Ficção Científica"]
    },
    {
        "titulo": "Oppenheimer",
        "tipo": "filme",
        "image_url": "https://br.web.img2.acsta.net/pictures/23/05/08/10/29/0695770.jpg",
        "url": "/filmes/oppenheimer/",
        "ano": 2023,
        "classificacao": 4.9,
        "duracao": "3h",
        "descricao": "A história do físico J. Robert Oppenheimer e seu papel crucial no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Biografia", "Drama", "Histórico"]
    },
      {
        "titulo": "Mad Max: The Wasteland",
        "tipo": "filme",
        "image_url": "https://m.media-amazon.com/images/M/MV5BMTZiOGFlNTktYmE0ZS00OTI5LTg0YzEtYWNjZjEwZjQ3OWMyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "url": "/filmes/mad-max-the-wasteland/",
        "ano": 2024,
        "classificacao": 4.5,
        "duracao": "2h",#estimativa
        "descricao": "Ainda sem sinopse.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
    {
       "titulo": "Godzilla e Kong: O Novo Império",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/24/02/28/15/47/0426941.png",
        "url": "/filmes/godzilla-e-kong-o-novo-imperio/",
        "ano": 2024,
        "classificacao": 4.8,
        "duracao": "1h 55m",
        "descricao": "Kong e Godzilla se unem contra uma ameaça colossal escondida no interior da Terra, desafiando sua própria existência e a da humanidade.",
        "categoria": "Filmes",
        "classificacao_idade": "12",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
     {
        "titulo": "Madame Teia",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCMhj0iCBYLho10Dt3-puUzb2DMJKZ4wKztmC0kLA4KipJ3q1t",
        "url": "/filmes/madame-teia/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 45m",
        "descricao": "Cassandra Webb é uma paramédica em Manhattan que começa a ter visões. Forçada a confrontar revelações sobre seu passado, ela precisa proteger três jovens de um adversário misterioso.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
    {
        "titulo": "As Crianças Perdidas",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfrGea1lK_VKYrgbae38rpTXZKr3iV57-Dqpizfg6oSc72T7jh",
        "url": "/filmes/as-criancas-perdidas/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 31m",
        "descricao": "Em uma pequena cidade, as crianças começam a desaparecer, com o pai de uma das vítimas descobrindo segredos sombrios.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Terror", "Suspense"]
    },
      {
        "titulo": "Donzela",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTQopfiPuj3Y97H7J9_M-CCnMoSYnPr-4FQDAEORYvkh6TVBJZ",
        "url": "/filmes/donzela/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 49m",
        "descricao": "Uma jovem concorda em se casar com um príncipe charmoso, apenas para descobrir que tudo era uma armadilha. Jogada em uma caverna com um dragão que cospe fogo, ela precisa usar sua inteligência e vontade para sobreviver.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Ação", "Fantasia", "Aventura"]
    },
      {
        "titulo": "Sonic 3 - O Filme",
        "tipo": "filme",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/8/89/Sonic_The_Hedgehog_3_p%C3%B4ster.png",
        "url": "/filmes/sonic-3-o-filme/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 40m",#estimativa
        "descricao": "Ainda sem sinopse.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Aventura", "Comédia"]
    },
               {
        "titulo": "Mufasa: O Rei Leão",
        "tipo": "filme",
        "image_url": "https://lumiere-a.akamaihd.net/v1/images/7e31d6246c6f32fbb227b4739fb5440f_da23af1f.jpeg",
        "url": "/filmes/mufasa-o-rei-leao/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 50m", # Estimativa
        "descricao": "A história da origem de Mufasa, o pai de Simba.",
        "categoria": "Filmes",
        "classificacao_idade": "L",
        "generos": ["Animação", "Família", "Musical"]
    },
     {
        "titulo": "Zona de Risco",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQWOVR7fo4GAlHZntJ1mHKkA-vayIOpFllvx-0WFrIemcGr7Emt",
        "url": "/filmes/zona-de-risco/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 52m",  # Estimativa
        "descricao": "Um thriller de ação em uma zona de conflito.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Guerra", "Suspense"]
    },
     {
        "titulo": "Venom 3: A Última Rodada",
        "tipo": "filme",
        "image_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRaJR9l-d-cO5g9POq4IGKI2VgVwdmCO5YHPdDWSB3IsafRzbsa",
        "url": "/filmes/venom-3-a-ultima-rodada/",
        "ano": 2024,
        "classificacao": 4.9,
        "duracao": "1h 47m", #Estimativa
        "descricao": "Eddie Brock e Venom enfrentam uma última ameaça em sua jornada.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Ação", "Ficção Científica", "Suspense"]
    },
      {
        "titulo": "The Walking Dead",
        "tipo": "serie",
        "image_url": "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/78/35/82/20303823.jpg",
        "url": "/series/the-walking-dead/",
        "ano": 2010,
        "classificacao": 4.5,
        "temporadas": 11,
        "descricao": "Um grupo de sobreviventes luta para sobreviver em um mundo pós-apocalíptico dominado por zumbis.",
        "categoria": "Séries",
        "classificacao_idade": "18",
        "generos": ["Terror", "Suspense"]
    },
     {
        "titulo": "Dark",
        "tipo": "serie",
        "image_url": "https://resizing.flixster.com/lpJkDxnEFNQT1OWJjnmYfvpAHJ0=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjI2NjgyOS53ZWJw",
        "url": "/series/dark/",
        "ano": 2017,
        "classificacao": 4.8,
        "temporadas": 3,
        "descricao": "O desaparecimento de duas crianças em uma cidade alemã revela segredos obscuros e conexões entre quatro famílias.",
        "categoria": "Séries",
        "classificacao_idade": "16",
        "generos": ["Suspense", "Ficção Científica", "Drama"]
    },

   {
        "titulo": "Sintonia",
        "tipo": "serie",
        "image_url": "https://m.media-amazon.com/images/M/MV5BOWVjYTlhZGEtMGRmNS00NWU1LWE4NzQtYjE5OTdjNzBmZDI4XkEyXkFqcGc@._V1_.jpg",
        "url": "/series/sintonia/",
        "ano": 2019,
        "classificacao": 4.9,
        "temporadas": 5,
        "descricao": "A história de Doni, Nando e Rita, três amigos de infância que vivem na mesma favela em São Paulo, mas seguem caminhos diferentes na vida.",
        "categoria": "Séries",
        "classificacao_idade": "16",
        "generos": ["Drama", "Crime"]
    },
    {
        "titulo": "Você",
        "tipo": "serie",
        "image_url": "https://br.web.img3.acsta.net/pictures/18/12/31/02/49/2373131.jpg",
        "url": "/series/voce/",
        "ano": 2018,
        "classificacao": 4.9,
        "temporadas": 4,
        "descricao": "Um charmoso e obsessivo stalker usa as redes sociais para se aproximar de suas vítimas e se livrar de qualquer obstáculo em seu caminho.",
        "categoria": "Séries",
        "classificacao_idade": "18",
        "generos": ["Crime", "Drama", "Suspense"]
    },
    {
        "titulo": "The Last of Us",
        "tipo": "serie",
        "image_url": "https://br.web.img3.acsta.net/c_310_420/pictures/22/11/30/19/53/5856320.jpg",
        "url": "/series/the-last-of-us/",
        "ano": 2023,
        "classificacao": 4.9,
        "temporadas": 1,
        "descricao": "Em um mundo pós-apocalíptico, Joel é contratado para contrabandear Ellie, uma garota de 14 anos, para fora de uma zona de quarentena.",
        "categoria": "Séries",
        "classificacao_idade": "18",
        "generos": ["Ação", "Aventura", "Drama"]
    },
    {
        "titulo": "A Casa do Dragão",
        "tipo": "serie",
        "image_url": "https://m.media-amazon.com/images/M/MV5BM2QzMGVkNjUtN2Y4Yi00ODMwLTg3YzktYzUxYjJlNjFjNDY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "url": "/series/a-casa-do-dragao/",
        "ano": 2022,
        "classificacao": 4.9,
        "temporadas": 2,
        "descricao": "200 anos antes dos eventos de Game of Thrones, a Casa Targaryen governa Westeros, mas uma luta pelo poder ameaça destruir a dinastia. A Dança dos Dragões se aproxima.",
        "categoria": "Séries",
        "classificacao_idade": "18",
        "generos": ["Ação", "Aventura", "Fantasia"]
    },
    {
        "titulo": "Stranger Things",
        "tipo": "serie",
        "image_url": "https://sm.ign.com/ign_pt/tv/s/stranger-t/stranger-things_ry8g.jpg",
        "url": "/series/stranger-things/",
        "ano": 2016,
        "classificacao": 9.9,
        "temporadas": 5,
        "descricao": "Quando um garoto desaparece, sua mãe, um chefe de polícia e seus amigos devem confrontar forças aterrorizantes para trazê-lo de volta.",
        "categoria": "Séries",
        "classificacao_idade": "16",
        "generos": ["Drama", "Ficção Científica", "Terror"]
    },
    {
        "titulo": "Breaking Bad - A Química do Mal",
        "tipo": "serie",
        "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRcr0khV9t7IeOcVDRvC84eCW_5yidk-aWcf466252yFKNPAf5M",
        "url": "/series/breaking-bad/",
        "ano": 2008,
        "classificacao": 4.9,
        "temporadas": 5,
        "descricao": "Um professor de química do ensino médio diagnosticado com câncer de pulmão terminal decide cozinhar e vender metanfetamina para garantir o futuro financeiro de sua família.",
        "categoria": "Séries",
        "classificacao_idade": "18",
        "generos": ["Crime", "Drama", "Suspense"]
    },
    {
        "titulo": "Vikings",
        "tipo": "serie",
        "image_url": "https://m.media-amazon.com/images/M/MV5BOTFmZmExYTEtYmE0Mi00MzRmLWE4ZDYtOThiNzNlOTIyODljXkEyXkFqcGc@._V1_.jpg",
        "url": "/series/vikings/",
        "ano": 2013,
        "classificacao": 4.9,
        "temporadas": 6,
        "descricao": "As aventuras épicas do viking Ragnar Lothbrok e sua jornada para se tornar rei.",
        "categoria": "Séries",
        "classificacao_idade": "18",
        "generos": ["Ação", "Aventura", "Drama", "Histórico", "Guerra"]
    },
    {
        "titulo": "Loki",
        "tipo": "serie",
        "image_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSHel80alzgYyna6UG8WpsVmyg-rM5f_zl5Ta_UnAHzIFA4nb6l",
        "url": "/series/loki/",
        "ano": 2021,
        "classificacao": 4.9,
        "temporadas": 2,
        "descricao": "Loki, o deus da travessura, viaja através do tempo e do espaço para corrigir as linhas do tempo e impedir uma ameaça ainda maior.",
        "categoria": "Séries",
        "classificacao_idade": "12",
        "generos": ["Ação", "Aventura", "Fantasia"]
    },
    {
        "titulo": "Por Lugares Incríveis",
        "tipo": "filme",
        "image_url": "https://infinitasvidas.wordpress.com/wp-content/uploads/2020/02/por-lugares-incriveis-poster.png",
        "url": "/filmes/por-lugares-incriveis/",
        "ano": 2020,
        "classificacao": 5.5,
        "duracao": "1h 48m",
        "descricao": "Dois adolescentes com problemas emocionais se conectam em uma jornada de autodescoberta.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Drama", "Romance"]
    },
    {
        "titulo": "A vida em um ano",
        "tipo": "filme",
        "image_url": "https://play-lh.googleusercontent.com/KtzLv7v4SBhoY5T-Pn57RQloLD4-I-HfTsgjnVaPHYh28QsZ0zyRl9lVkIjfBzmuRyCWcArnBTnkXNv7DQlc",
        "url": "/filmes/a-vida-em-um-ano/",
        "ano": 2020,
        "classificacao": 5.0,
        "duracao": "1h 47m",
        "descricao": "Um jovem decide proporcionar um ano inesquecível para sua namorada que está com uma doença terminal.",
        "categoria": "Filmes",
        "classificacao_idade": "14",
        "generos": ["Drama", "Romance"]
    },
    {
        "titulo": "Esquadrão 6",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/pictures/19/11/14/15/36/5224064.png",
        "url": "/filmes/esquadrao-6/",
        "ano": 2019,
        "classificacao": 4.7,
        "duracao": "2h 8m",
        "descricao": "Um bilionário simula a própria morte e recruta uma equipe para combater o crime.",
        "categoria": "Filmes",
        "classificacao_idade": "18",
        "generos": ["Ação", "Suspense"]
    },
     {
        "titulo": "Invasão Secreta",
        "tipo": "serie",
        "image_url": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTB2N3NcdUASK2rUyorALbjgzT-36PbBYYTZVDkw5vxn_tFX86w",
        "url": "/series/invasao-secreta/",
        "ano": 2023,
        "classificacao": 3.2,
        "temporadas": 1,
        "descricao": "Nick Fury descobre uma invasão alienígena na Terra e precisa impedir uma guerra iminente.",
        "categoria": "Séries",
        "classificacao_idade": "16",
        "generos": ["Ação", "Aventura", "Ficção Científica"]
    },
     {
        "titulo": "Sr. & Sra. Smith",
        "tipo": "filme",
        "image_url": "https://br.web.img3.acsta.net/medias/nmedia/18/91/11/31/20130070.jpg",
        "url": "/filmes/sr-e-sra-smith/",
        "ano": 2005,
        "classificacao": 5.9,
        "duracao": "2h",
        "descricao": "Um casal de assassinos descobre que foram contratados para se matarem.",
        "categoria": "Filmes",
        "classificacao_idade": "16",
        "generos": ["Ação", "Comédia", "Romance"]
    },
    {
       "titulo": "Superman & Lois",
        "tipo": "serie",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/b/bc/Superman%26Lois.jpg",
        "url": "/series/superman-e-lois/",
        "ano": 2021,
        "classificacao": 5.0,
        "temporadas": 4,
        "descricao": "Superman e Lois Lane retornam para Smallville para criar seus filhos adolescentes."
        ,'categoria': "Séries",
        "classificacao_idade": "12",
         "generos": ["Ação", "Aventura", "Drama", "Ficção Científica"]
    },
   {
        "titulo": "Duna: Profecia",
        "tipo": "serie",
        "image_url": "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Ff4cf02f4-34c8-4c19-bd01-20a16b29bf92_2000x3000.jpeg",
        "url": "/series/duna-profecia/",
        "ano": 2024,
        "classificacao": 7.9,
        "temporadas": 1,
        "descricao": "Situada no vasto universo de Duna, criado por Frank Herbert, e milênios antes dos eventos de 'Duna', a série acompanha duas irmãs Harkonnen enquanto combatem forças que ameaçam o futuro da humanidade e estabelecem a lendária seita que ficaria conhecida como Bene Gesserit."
         ,'categoria': "Séries",
        "classificacao_idade": "14",
        "generos": ["Drama", "Ficção Científica"]
    },
    {
        "titulo": "Vikings: Valhalla",
        "tipo": "serie",
        "image_url": "https://m.media-amazon.com/images/M/MV5BYWFjYmMxMjMtMGE2ZC00YWZhLTgzNDYtYTA3ODA2MDg2NTA4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "url": "/series/vikings-valhalla/",
        "ano": 2022,
        "classificacao": 6.5,
        "temporadas": 3,
        "descricao": "Em meados do século XI, as aventuras épicas de alguns dos Vikings mais famosos de todos os tempos: Leif Eriksson, Freydís Eiríksdóttir, Harald Hardrada e o rei normando Guilherme, o Conquistador."
         ,'categoria': "Séries",
        "classificacao_idade": "18",
         "generos": ["Ação", "Aventura", "Drama", "Histórico", "Guerra"]
    },
  {
        "titulo": "Wandinha",
        "tipo": "serie",
        "image_url": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQcbz7xl0ZKBUISzS0R6YSvLsGbuS4FoffVjytotNwjfvawroR",
        "url": "/series/wandinha/",
        "ano": 2022,
        "classificacao": 8.4,
        "temporadas":2,
        "descricao": "Acompanhe Wandinha Addams em seus anos como estudante na peculiar Academia Nevermore, onde tenta dominar sua habilidade psíquica emergente, investigar uma série de assassinatos que aterrorizam a cidade local e resolver o mistério sobrenatural que envolveu seus pais 25 anos atrás."
         ,'categoria': "Séries",
        "classificacao_idade": "14",
        "generos": ["Comédia", "Fantasia", "Família"]
    },
   {
        "titulo": "Round 6",
        "tipo": "serie",
        "image_url": "https://cdn.oantagonista.com/uploads/2024/12/Round-6-Prepara-se-para-segunda-temporada-1-819x1024.jpeg",
        "url": "/series/round-6/",
        "ano": 2021,
        "classificacao": 8.9,
        "temporadas":1,
        "descricao": "Centenas de jogadores falidos aceitam um estranho convite para competir em jogos infantis. Dentro de um local esperando por eles está um prêmio sedutor com apostas altas, mortais."
         ,'categoria': "Séries",
        "classificacao_idade": "18",
       "generos": ["Drama", "Suspense"]
    },
  {
        "titulo": "Euphoria",
        "tipo": "serie",
        "image_url": "https://m.media-amazon.com/images/M/MV5BZjVlN2M2N2MtOWViZC00MzIxLTlhZWEtMTIwNDIwMzE3ZWJiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "url": "/series/euphoria/",
        "ano": 2019,
        "classificacao": 7.9,
        "temporadas": 2,
        "descricao": "Um grupo de estudantes do ensino médio luta contra problemas de drogas, sexo e violência."
         ,'categoria': "Séries",
        "classificacao_idade": "18",
        "generos": ["Drama", "Romance"]
    },
    {
        "titulo": "Homens de Terno",
        "tipo": "serie",
        "image_url": "https://m.media-amazon.com/images/M/MV5BYmE4MmNjZjUtNTEyNy00NTZiLWE4NTktYjM2NjBhYzQ1N2IzXkEyXkFqcGc@._V1_.jpg",
        "url": "/series/homens-de-terno/",
        "ano": 2011,
        "classificacao": 8.9,
        "temporadas": 9,
        "descricao": "Mike Ross, um brilhante estudante que nunca foi à faculdade de direito, consegue um emprego em um importante escritório de advocacia em Nova York."
         ,'categoria': "Séries",
        "classificacao_idade": "16",
        "generos": ["Comédia", "Drama"]
    },
     {
    "titulo": "The Boys",
    "tipo": "serie",
    "image_url": "https://sm.ign.com/ign_br/screenshot/default/the-boys-season-2-poster-butcher_z1eg.jpg",
    "url": "/series/theboys/",
    "ano": 2019,
    "classificacao": 3.8,
    "temporadas": 5,
    "descricao": "Um grupo de vigilantes se propõe a derrubar super-heróis corruptos que abusam de seus poderes.",
    "categoria": "Séries",
    "classificacao_idade": "18",
    "generos": ["Ação", "Comédia", "Crime"]
  },
  {
    "titulo": "Game of Thrones",
    "tipo": "serie",
    "image_url": "https://br.web.img3.acsta.net/pictures/19/03/21/16/15/4239577.jpg",
    "url": "/series/gameofthrones/",
    "ano": 2011,
    "classificacao": 3.9,
    "temporadas": 8,
    "descricao": "Em uma terra onde os verões duram décadas e os invernos podem durar uma vida, reis e rainhas lutam... pelo Trono de Ferro.",
    "categoria": "Séries",
    "classificacao_idade": "18",
     "generos": ["Ação", "Aventura", "Drama", "Fantasia", "Guerra"]
  },
  {
    "titulo": "The Witcher",
    "tipo": "serie",
    "image_url": "https://br.web.img3.acsta.net/pictures/19/11/29/17/57/5161763.jpg",
    "url": "/series/thewitcher/",
    "ano": 2019,
    "classificacao": 2.6,
    "temporadas": 3,
    "descricao": "Geralt de Rívia, um caçador de monstros mutante, luta para encontrar seu lugar em um mundo onde as pessoas provam ser mais perversas que as bestas.",
    "categoria": "Séries",
    "classificacao_idade": "16",
    "generos": ["Ação", "Aventura", "Fantasia"]
  },
  {
    "titulo": "O Último Reino",
    "tipo": "serie",
    "image_url": "https://media.fstatic.com/-sl4LDVFrHBr9l4erpgFkNjEHOk=/322x478/smart/filters:format(webp)/media/movies/covers/2022/03/the-last-kingdom-5-25poster.jpg",
    "url": "/series/oultimoreino/",
    "ano": 2015,
    "classificacao": 2.4,
    "temporadas": 5,
    "descricao": "Enquanto o rei Alfred, o Grande, defende seu reino de invasores nórdicos, Uhtred - nascido saxão, mas criado por vikings - busca reivindicar seus direitos ancestrais.",
    "categoria": "Séries",
    "classificacao_idade": "16",
    "generos": ["Ação", "Drama", "Histórico", "Guerra"]
  },
  {
    "titulo": "Tróia: Queda de uma Cidade",
    "tipo": "serie",
    "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSqdprTOTDfDLNDo7SbP5IzXOm56pBXpWiLDJqsM1ZPyZ1QmhM-",
    "url": "/series/troia/",
    "ano": 2018,
    "classificacao": 1.9,
    "temporadas": 1,
    "descricao": "Uma história de amor e intriga ambientada durante o cerco de Tróia, onde a família real se encontra dividida e em meio à guerra.",
    "categoria": "Séries",
    "classificacao_idade": "16",
       "generos": ["Drama", "Histórico", "Romance", "Guerra"]
  },
  {
        "titulo": "A Roda do Tempo",
        "tipo": "serie",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-5zl2WfCHBcEUgbjBAwrFoPU61SdtqBWNUYkqFee-1C9fibHn",
        "url": "/series/arodadotempo/",
        "ano": 2021,
        "classificacao": 1.4,
        "temporadas": 2,
        "descricao": "Em um mundo onde a magia existe, mas apenas as mulheres podem usá-la, uma mulher embarca em uma jornada perigosa com cinco jovens, um dos quais é profetizado para salvar ou destruir a humanidade.",
        "categoria": "Séries",
        "classificacao_idade": "14",
        "generos": ["Ação", "Aventura", "Fantasia"]
    },
    {
        "titulo": "Peaky Blinders",
        "tipo": "serie",
        "image_url": "https://m.media-amazon.com/images/M/MV5BM2ZiNThlNzItNmY3Ny00NjA2LWJlMjItNTk1NDI3MDMyMTk4XkEyXkFqcGc@._V1_.jpg",
        "url": "/series/peakyblinders/",
        "ano": 2013,
        "classificacao": 3.1,
        "temporadas": 6,
        "descricao": "Uma saga familiar centrada em uma gangue liderada por Thomas Shelby, ambientada em Birmingham, Inglaterra, após a Primeira Guerra Mundial.",
        "categoria": "Séries",
        "classificacao_idade": "18",
        "generos": ["Crime", "Drama", "Histórico"]
    },
    {
        "titulo": "Brooklyn Nine-Nine",
        "tipo": "serie",
        "image_url": "https://upload.wikimedia.org/wikipedia/pt/5/53/Brooklyn_Nine-Nine-4.jpg",
        "url": "/series/brooklyn99/",
        "ano": 2013,
        "classificacao": 1.6,
        "temporadas": 8,
        "descricao": "Jake Peralta, um detetive talentoso, mas imaturo, entra em conflito com seu novo comandante, o capitão Ray Holt.",
        "categoria": "Séries",
        "classificacao_idade": "12",
        "generos": ["Comédia", "Crime"]
    },
    {
        "titulo": "Lista Negra",
        "tipo": "serie",
        "image_url": "https://images.justwatch.com/poster/307413721/s718/the-blacklist.jpg",
        "url": "/series/listanegra/",
        "ano": 2013,
        "classificacao": 3.5,
        "temporadas": 10,
        "descricao": "Um criminoso internacional se entrega e se oferece para ajudar o FBI a capturar outros criminosos, mas apenas se trabalhar com Elizabeth Keen.",
        "categoria": "Séries",
        "classificacao_idade": "16",
        "generos": ["Crime", "Drama", "Suspense"]
    },
  


  {
    "titulo": "HAIKYU!!",
    "tipo": "anime",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVIHdPj64oMGacY6LFvh17Bp9KT1-uF-Nyqg&s",
    "url": "/animes/haikyuu/",
    "ano": 2014,
    "classificacao": 1.8,
    "temporadas": 4,
    "descricao": "Um estudante do ensino médio ganha paixão pelo voleibol após assistir a uma partida na TV.",
    "categoria": "Animes",
    "classificacao_idade": "10",
    "generos": ["Animação", "Comédia", "Esporte"]
  },
  {
    "titulo": "Fullmetal Alchemist: Brotherhood",
    "tipo": "anime",
    "image_url": "https://m.media-amazon.com/images/M/MV5BMzNiODA5NjYtYWExZS00OTc4LTg3N2ItYWYwYTUyYmM5MWViXkEyXkFqcGc@._V1_.jpg",
    "url": "/animes/fullmetalalchemist/",
    "ano": 2009,
    "classificacao": 2.1,
    "temporadas": 1,
    "descricao": "Dois irmãos alquimistas embarcam em uma jornada para restaurar seus corpos após um ritual desastroso.",
    "categoria": "Animes",
    "classificacao_idade": "14",
     "generos": ["Ação", "Aventura", "Fantasia"]
  },
  {
    "titulo": "Hellsing",
    "tipo": "anime",
    "image_url": "https://m.media-amazon.com/images/M/MV5BYWFmMWE4YTMtMWViNS00NzI5LTljZGUtMGM1YTFkNmMzZjE3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "url": "/animes/hellsing/",
    "ano": 2001,
    "classificacao": 1.7,
    "temporadas": 1,
    "descricao": "Uma organização secreta caça vampiros para proteger a Inglaterra.",
    "categoria": "Animes",
    "classificacao_idade": "18",
     "generos": ["Ação", "Terror", "Suspense"]
  },
  {
    "titulo": "Devilman Crybaby",
    "tipo": "anime",
    "image_url": "https://m.media-amazon.com/images/M/MV5BMjRjOGI4M2YtMGQ4NC00OTk3LTg4MWItYjBjYzNiOGI0Y2ZkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "url": "/animes/devilmancrybaby/",
    "ano": 2018,
    "classificacao": 1.6,
    "temporadas": 1,
    "descricao": "Um jovem tímido se funde com um demônio para lutar contra outras criaturas malignas.",
    "categoria": "Animes",
    "classificacao_idade": "18",
     "generos": ["Ação", "Terror", "Suspense"]
  },
  {
    "titulo": "JUJUTSU KAISEN",
    "tipo": "anime",
    "image_url": "https://br.web.img3.acsta.net/pictures/20/09/14/10/31/4875617.jpg",
    "url": "/animes/jujutsukaisen/",
    "ano": 2020,
    "classificacao": 3.5,
    "temporadas": 2,
    "descricao": "Um estudante se torna hospedeiro de um espírito amaldiçoado para lutar contra outras maldições.",
    "categoria": "Animes",
    "classificacao_idade": "16",
     "generos": ["Ação", "Fantasia", "Suspense"]
  },
  {
    "titulo": "Olhos de Gato",
    "tipo": "anime",
    "image_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR0wabzDYboIKONWTqs6errm3R5owHvLos-0pA1GHJFsc5SwD1r",
    "url": "/animes/olhosdegato/",
    "ano": 2023,
    "classificacao": 3.1,
    "temporadas": 2,
    "descricao": "Três irmãs administram um café durante o dia e roubam obras de arte à noite.",
    "categoria": "Animes",
    "classificacao_idade": "12",
     "generos": ["Ação", "Comédia", "Crime"]
  },
  {
    "titulo": "Demon Slayer - Mugen Train: O Filme",
    "tipo": "anime",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzHliur3CAhL0y8rz4oA00hkPtEktWQH90g&s",
    "url": "/animes/demonslayerfilm/",
    "ano": 2020,
    "classificacao": 3.4,
    "temporadas": 4,
    "descricao": "Tanjiro e seus companheiros embarcam em uma missão para derrotar um demônio em um trem.",
    "categoria": "Filmes",
    "classificacao_idade": "16",
    "generos": ["Ação", "Aventura", "Fantasia"]
  },
  {
    "titulo": "Violet Evergarden - O Filme",
    "tipo": "anime",
    "image_url": "https://br.web.img2.acsta.net/pictures/20/03/25/11/57/1582502.jpg",
    "url": "/animes/violetevergardenfilm/",
    "ano": 2020,
    "classificacao": 2.2,
    "temporadas": 1,
    "descricao": "Uma ex-soldada tenta se reintegrar à sociedade escrevendo cartas para outras pessoas.",
    "categoria": "Filmes",
    "classificacao_idade": "12",
    "generos": ["Drama", "Animação"]
  },
  {
    "titulo": "Naruto Shippuden",
    "tipo": "anime",
    "image_url": "https://m.media-amazon.com/images/M/MV5BNTk3MDA1ZjAtNTRhYS00YzNiLTgwOGEtYWRmYTQ3NjA0NTAwXkEyXkFqcGc@._V1_.jpg",
    "url": "/animes/narutoshippuden/",
    "ano": 2007,
    "classificacao": 2.9,
    "temporadas": 21,
    "descricao": "Naruto retorna à sua vila para proteger seus amigos e enfrentar novas ameaças.",
    "categoria": "Animes",
    "classificacao_idade": "14",
     "generos": ["Ação", "Aventura", "Fantasia"]
  },
  {
    "titulo": "SAKAMOTO DAYS",
    "tipo": "anime",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrZIJPAwIYtxoEoTDUh-Fi4ihnCHsazk1zbQ&s",
    "url": "/animes/sakamotodays/",
    "ano": 2025,
    "classificacao": 1.6,
    "temporadas": 1,
    "descricao": "Um ex-assassino tenta levar uma vida pacata como dono de uma loja de conveniência.",
    "categoria": "Animes",
    "classificacao_idade": "16",
     "generos": ["Ação", "Comédia"]
  },

  {
    "titulo": "Beleza Verdadeira",
    "tipo": "dorama",
    "image_url": "https://br.web.img3.acsta.net/c_310_420/pictures/22/05/09/19/18/4364019.jpg",
    "url": "/doramas/belezaverdadeira/",
    "ano": 2020,
    "classificacao": 3.0,
    "temporadas": 1,
    "descricao": "Uma estudante que usa maquiagem para esconder suas inseguranças enfrenta desafios no amor e na autoaceitação.",
    "categoria": "Doramas",
    "classificacao_idade": "14",
    "generos": ["Comédia", "Romance"]
  },
  {
    "titulo": "Nosso Destino",
    "tipo": "dorama",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQFtSOewd5fI0d0c0NtDu3uc7iuAvqb2kZQQ&s",
    "url": "/doramas/nossodestino/",
    "ano": 2023,
    "classificacao": 1.9,
    "temporadas": 1,
    "descricao": "Um romance entre uma funcionária pública e um advogado, com uma maldição familiar no meio do caminho.",
    "categoria": "Doramas",
    "classificacao_idade": "12",
      "generos": ["Drama", "Fantasia", "Romance"]
  },
  {
    "titulo": "Descendentes do Sol",
    "tipo": "dorama",
    "image_url": "https://images.justwatch.com/poster/306601630/s718/descendants-of-the-sun.jpg",
    "url": "/doramas/descendentesdosol/",
    "ano": 2016,
    "classificacao": 2.7,
    "temporadas": 1,
    "descricao": "Um soldado das forças especiais e uma médica se apaixonam em meio a conflitos em um país devastado pela guerra.",
    "categoria": "Doramas",
    "classificacao_idade": "14",
       "generos": ["Ação", "Drama", "Romance"]
  },
  {
    "titulo": "O que Há de Errado com a Secretária Kim?",
    "tipo": "dorama",
    "image_url": "https://upload.wikimedia.org/wikipedia/pt/1/10/What%27s_Wrong_with_Secretary_Kim.jpg",
    "url": "/doramas/secretariakim/",
    "ano": 2018,
    "classificacao": 1.7,
    "temporadas": 1,
    "descricao": "Um vice-presidente narcisista tenta impedir que sua eficiente secretária se demita.",
    "categoria": "Doramas",
    "classificacao_idade": "12",
         "generos": ["Comédia", "Romance"]
  },
  {
    "titulo": "Round 6",
    "tipo": "dorama",
    "image_url": "https://cdn.oantagonista.com/uploads/2024/12/Round-6-Prepara-se-para-segunda-temporada-1-819x1024.jpeg",
    "url": "/doramas/round6/",
    "ano": 2021,
    "classificacao": 3.3,
    "temporadas": 1,
    "descricao": "Pessoas endividadas são convidadas a participar de jogos mortais com um prêmio em dinheiro em jogo.",
    "categoria": "Doramas",
    "classificacao_idade": "18",
    "generos": ["Drama", "Suspense"]
  },
  {
    "titulo": "Goblin",
    "tipo": "dorama",
    "image_url": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT3QC_0G4TcZK_zksrUekNvTHBvCDwREhKr24Q5XZbYkxPR5FPG",
    "url": "/doramas/goblin/",
    "ano": 2016,
    "classificacao": 2.9,
    "temporadas": 1,
    "descricao": "Um goblin imortal precisa encontrar sua noiva humana para acabar com sua imortalidade.",
    "categoria": "Doramas",
    "classificacao_idade": "14",
       "generos": ["Comédia", "Fantasia", "Romance"]
  },
  {
    "titulo": "A Love So Beautiful",
    "tipo": "dorama",
    "image_url": "https://upload.wikimedia.org/wikipedia/pt/0/0d/A_Love_So_Beautiful_poster.jpg",
    "url": "/doramas/alovesobeautiful/",
    "ano": 2020,
    "classificacao": 2.0,
    "temporadas": 1,
    "descricao": "Uma estudante persistente tenta conquistar o coração de seu vizinho frio e distante.",
    "categoria": "Doramas",
    "classificacao_idade": "Livre",
         "generos": ["Comédia", "Romance"]
  },
  {
    "titulo": "Pousando no Amor",
    "tipo": "dorama",
    "image_url": "https://www.constancezahn.com/wp-content/uploads/2022/04/foto-capa-serie-dorama-pousando-no-amor.jpg",
    "url": "/doramas/pousandonoamor/",
    "ano": 2019,
    "classificacao": 1.4,
    "temporadas": 1,
    "descricao": "Uma herdeira sul-coreana faz um pouso forçado na Coreia do Norte e é ajudada por um oficial do exército.",
    "categoria": "Doramas",
    "classificacao_idade": "14",
        "generos": ["Comédia", "Drama", "Romance", "Guerra"]
  },
  {
    "titulo": "Cães de Caça",
    "tipo": "dorama",
    "image_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR_kz82WigUMzcw62YNswlairqZ3vbfldZk6QptatqeSnbtQ-YU",
    "url": "/doramas/caesdecaca/",
    "ano": 2023,
    "classificacao": 3.7,
    "temporadas": 1,
    "descricao": "Jovens se unem para derrubar agiotas implacáveis que exploram pessoas desesperadas.",
    "categoria": "Doramas",
    "classificacao_idade": "16",
        "generos": ["Ação", "Crime", "Drama"]
  },
  {
    "titulo": "Sweet Home",
    "tipo": "dorama",
    "image_url": "https://p2.trrsf.com/image/fget/cf/774/0/images.terra.com/2024/06/21/1460236730-enussws3maindateannouncementvertical27x40rgbpre1.jpg",
    "url": "/doramas/sweethome/",
    "ano": 2020,
    "classificacao": 3.3,
    "temporadas": 3,
    "descricao": "Adolescente problemático e outros moradores de um prédio lutam para sobreviver em meio a monstros.",
    "categoria": "Doramas",
    "classificacao_idade": "18",
         "generos": ["Terror", "Fantasia", "Suspense"]
  },

  {
    "titulo": "Nosso Planeta",
    "tipo": "documentario",
    "image_url": "https://images.justwatch.com/poster/320144010/s718/our-planet.jpg",
    "url": "/documentarios/nossoplaneta/",
    "ano": 2019,
    "classificacao": 2.5,
    "temporadas": 1,
    "descricao": "Documentário explora a beleza natural e a fragilidade do planeta Terra.",
    "categoria": "Documentários",
    "classificacao_idade": "Livre",
    "generos": ["Documentário"]
  },
  {
    "titulo": "F1: Dirigir para Viver",
    "tipo": "documentario",
    "image_url": "https://cinepop.com.br/wp-content/uploads/2022/02/f1-dirigir-para-viver-2.png",
    "url": "/documentarios/f1/",
    "ano": 2018,
    "classificacao": 3.6,
    "temporadas": 6,
    "descricao": "Série documental acompanha os bastidores da Fórmula 1, mostrando a vida de pilotos, equipes e proprietários.",
    "categoria": "Documentários",
    "classificacao_idade": "12",
    "generos": ["Documentário", "Esporte"]
  },
  {
    "titulo": "O Dilema das Redes",
    "tipo": "documentario",
    "image_url": "https://biblioteca.letras.ufrj.br/wp-content/uploads/2023/06/o-dilema-das-redes-choque-assimilacao-solucao-social-media.jpeg",
    "url": "/documentarios/odilema/",
    "ano": 2020,
    "classificacao": 2.6,
    "temporadas": 1,
    "descricao": "Especialistas discutem o impacto das redes sociais na sociedade e os perigos da manipulação algorítmica.",
    "categoria": "Documentários",
    "classificacao_idade": "14",
    "generos": ["Documentário"]
  },
  {
    "titulo": "Amy",
    "tipo": "documentario",
    "image_url": "https://br.web.img3.acsta.net/c_310_420/pictures/15/05/20/17/08/388158.jpg",
    "url": "/documentarios/amy/",
    "ano": 2015,
    "classificacao": 1.8,
    "temporadas": 1,
    "descricao": "Documentário sobre a vida e a carreira da cantora Amy Winehouse.",
    "categoria": "Documentários",
    "classificacao_idade": "16",
       "generos": ["Biografia", "Documentário", "Musical"]
  },
  {
    "titulo": "A 13ª Emenda",
    "tipo": "documentario",
    "image_url": "https://upload.wikimedia.org/wikipedia/pt/d/d6/13th_%28filme%29.png",
    "url": "/documentarios/a13emenda/",
    "ano": 2016,
    "classificacao": 2.2,
    "temporadas": 1,
    "descricao": "Documentário analisa o sistema prisional dos Estados Unidos e sua relação com a história da escravidão.",
    "categoria": "Documentários",
    "classificacao_idade": "14",
    "generos": ["Documentário", "Histórico"]
  },
  {
    "titulo": "Pelé",
    "tipo": "documentario",
    "image_url": "https://br.web.img3.acsta.net/pictures/21/02/04/14/22/4488128.jpg",
    "url": "/documentarios/pele/",
    "ano": 2021,
    "classificacao": 3.8,
    "temporadas": 1,
    "descricao": "Documentário sobre a vida e a carreira do lendário jogador de futebol Pelé.",
    "categoria": "Documentários",
    "classificacao_idade": "Livre",
    "generos": ["Biografia", "Documentário", "Esporte"]
  },
  {
    "titulo": "Virunga",
    "tipo": "documentario",
    "image_url": "https://upload.wikimedia.org/wikipedia/pt/1/13/Virunga.png",
    "url": "/documentarios/virunga/",
    "ano": 2014,
    "classificacao": 1.3,
    "temporadas": 1,
    "descricao": "Documentário acompanha os guardas florestais que arriscam suas vidas para proteger o Parque Nacional de Virunga, no Congo.",
    "categoria": "Documentários",
    "classificacao_idade": "12",
    "generos": ["Aventura", "Documentário"]
  },
  {
    "titulo": "Senna",
    "tipo": "documentario",
    "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQWOVR7fo4GAlHZntJ1mHKkA-vayIOpFllvx-0WFrIemcGr7Emt",
    "url": "/documentarios/senna/",
    "ano": 2010,
    "classificacao": 3.9,
    "temporadas": 1,
    "descricao": "Documentário sobre a vida e a morte do piloto de Fórmula 1 Ayrton Senna.",
    "categoria": "Documentários",
    "classificacao_idade": "12",
     "generos": ["Biografia", "Documentário", "Esporte"]
  },
  {
    "titulo": "A queda de Diddy",
    "tipo": "documentario",
    "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ7p9VsNOme6Jo7wxyqVl1XgUkNW3OAubY20Z-KSntmEjSrMI-b",
    "url": "/documentarios/aquedadodiddy/",
    "ano": 2024,
    "classificacao": 1.7,
    "temporadas": 1,
    "descricao": "A ascensão e queda de Diddy, mostrando seu império e o que levou ao fim",
    "categoria": "Documentários",
    "classificacao_idade": "18",
     "generos": ["Biografia", "Crime", "Documentário"]
  },
  {
    "titulo": "A Casa que os Dragões Construíram",
    "tipo": "documentario",
    "image_url": "https://images.justwatch.com/poster/319496865/s718/house-of-the-dragon-the-house-that-dragons-built.jpg",
    "url": "/documentarios/acasaqueosdragoesconstruiram/",
    "ano": 2022,
    "classificacao": 2.5,
    "temporadas": 1,
    "descricao": "Documentário sobre a criação da serie House of the Dragon",
    "categoria": "Documentários",
    "classificacao_idade": "16",
      "generos": ["Documentário"]
   },
        # Adicione mais mídias conforme necessário
    ]

    for midia_data in midias:
        # Remove os campos ManyToMany (generos e atores) do dicionário
        generos_data = midia_data.pop('generos', [])
        atores_data = midia_data.pop('atores', [])

        # Cria o objeto Midia
        midia = Midia(**midia_data)
        midia.save()

        # Adiciona os gêneros
        if generos_data:
            generos = Genero.objects.filter(nome__in=generos_data)
            midia.generos.set(generos)

        # Adiciona os atores
        if atores_data:
            atores = [Ator.objects.get_or_create(nome=nome)[0] for nome in atores_data]
            midia.atores.set(atores)

        print(f"Adicionado: {midia.titulo} ({midia.tipo})")

    print("Banco de dados populado com sucesso!")

# Executa o script
if __name__ == '__main__':
    print("Populando o banco de dados...")
    populate_db()