# Generated by Django 5.1.6 on 2025-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musica',
            name='capa',
            field=models.ImageField(upload_to='capas/'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.IntegerField(help_text='Duração em segundos'),
        ),
    ]
