# Generated by Django 5.1.6 on 2025-03-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0002_musica_visualizacoes_alter_musica_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='arquivo',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='musica',
            name='capa',
            field=models.URLField(max_length=500),
        ),
    ]
