# Generated by Django 5.1.6 on 2025-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0007_album_artista_alter_musica_album_album_artista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
    ]
