# Generated by Django 3.1 on 2025-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0009_musica_duracao_album_musica_genero_musica_link_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
