# Generated by Django 5.1.6 on 2025-03-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0010_auto_20250310_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='banner_artista',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='capa_artista',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
