# Generated by Django 3.1 on 2025-03-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0011_musica_banner_artista_musica_capa_artista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
