# Generated by Django 5.1.6 on 2025-03-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0027_alter_assinatura_id_alter_conteudo_id_and_more'),
        ('spacemusic', '0012_auto_20250311_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MusicaTocadaRecentemente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_reproducao', models.DateTimeField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacemusic.musica')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas_tocadas', to='contas.perfil')),
            ],
            options={
                'ordering': ['-data_hora_reproducao'],
                'unique_together': {('perfil', 'musica')},
            },
        ),
    ]
