# Generated by Django 5.1.6 on 2025-03-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacebot', '0002_auto_20250310_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
