# Generated by Django 3.0 on 2025-02-14 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nome_usuario', models.CharField(max_length=100, unique=True)),
                ('plano', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_perfis/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(max_length=50, verbose_name='Plano da Assinatura')),
                ('tipo_pagamento', models.CharField(max_length=20, verbose_name='Tipo de Pagamento')),
                ('numero_cartao_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Número do Cartão (Hash)')),
                ('nome_cartao_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nome no Cartão (Hash)')),
                ('validade_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Validade (Hash)')),
                ('cvv_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='CVV (Hash)')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('proxima_cobranca', models.DateField(blank=True, null=True, verbose_name='Próxima Cobrança')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
