# Generated by Django 5.1.2 on 2025-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_remove_assinatura_cvv_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='cvv_criptografado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CVV (Criptografado)'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='nome_cartao_criptografado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome no Cartão (Criptografado)'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='numero_cartao_criptografado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Número do Cartão (Criptografado)'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='validade_criptografada',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Validade (Criptografada)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
