# Generated by Django 5.1.2 on 2025-02-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_rename_ultimo_acesso_dispositivo_ultima_data_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='sistema_operacional',
            field=models.CharField(max_length=500),
        ),
    ]
