# Generated by Django 5.1.2 on 2025-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_alter_dispositivo_sistema_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='navegador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='sistema_operacional',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ultima_data_login',
            field=models.DateField(auto_now=True),
        ),
    ]
