# Generated by Django 5.1.2 on 2025-02-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_dispositivo_via_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='pais',
            field=models.CharField(blank=True, default='BR', max_length=50, null=True),
        ),
    ]
