# Generated by Django 3.0 on 2025-03-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0014_conteudo_continueassistindo_favorito_historicovisualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='tipo_plano',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10),
        ),
    ]
