# Generated by Django 3.0 on 2025-03-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0015_assinatura_tipo_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_infantil',
            field=models.BooleanField(default=False),
        ),
    ]
