# Generated by Django 5.1.6 on 2025-03-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0029_delete_musicatocada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
    ]
