# Generated by Django 5.1.2 on 2025-01-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_usuario_plano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='plano',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('premium', 'Premium'), ('family', 'Family')], max_length=50, null=True),
        ),
    ]
