# Generated by Django 5.1.2 on 2025-02-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_auto_20250129_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
