# Generated by Django 3.0 on 2025-03-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pesquisa', '0006_auto_20250225_1841'),
        ('contas', '0014_conteudo_continueassistindo_favorito_historicovisualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodio_numero', models.IntegerField(default=0)),
                ('current_time', models.FloatField(default=0)),
                ('ultima_visualizacao', models.DateTimeField(auto_now=True)),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='pesquisa.Midia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='contas.Perfil')),
            ],
            options={
                'unique_together': {('perfil', 'midia', 'episodio_numero')},
            },
        ),
    ]
