# Generated by Django 5.1.6 on 2025-03-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproducao', '0002_auto_20250302_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
