# Generated by Django 3.1 on 2025-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproducao', '0005_alter_progresso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
