# Generated by Django 3.0 on 2025-03-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0006_auto_20250225_1841'),
        ('contas', '0014_conteudo_continueassistindo_favorito_historicovisualizacao'),
        ('reproducao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresso',
            name='ultima_visualizacao',
        ),
        migrations.AlterField(
            model_name='progresso',
            name='midia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.Midia'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Perfil'),
        ),
    ]
