# Generated by Django 5.1.2 on 2025-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_assinatura_id_alter_perfil_id_alter_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='cvv_hash',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='nome_cartao_hash',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='numero_cartao_hash',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='validade_hash',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cvv_criptografado',
            field=models.BinaryField(blank=True, null=True, verbose_name='CVV (Criptografado)'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='nome_cartao_criptografado',
            field=models.BinaryField(blank=True, null=True, verbose_name='Nome no Cartão (Criptografado)'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='numero_cartao_criptografado',
            field=models.BinaryField(blank=True, null=True, verbose_name='Número do Cartão (Criptografado)'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='validade_criptografada',
            field=models.BinaryField(blank=True, null=True, verbose_name='Validade (Criptografada)'),
        ),
    ]
