# Generated by Django 5.1.6 on 2025-03-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0005_musica_ano_musica_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(blank=True, choices=[('PHONK', 'Phonk'), ('FUNK', 'Funk'), ('TRAP', 'Trap'), ('SERTANEJO', 'Sertanejo'), ('PAGODE', 'Pagode'), ('ROCK', 'Rock'), ('POP', 'Pop'), ('JAZZ', 'Jazz'), ('ELETRONICA', 'Eletrônica'), ('RAP', 'Rap'), ('INDIE', 'Indie'), ('REGGAE', 'Reggae'), ('MPB', 'MPB'), ('CLASSICA', 'Clássica'), ('BLUES', 'Blues'), ('METAL', 'Metal'), ('COUNTRY', 'Country'), ('KPOP', 'K-Pop'), ('HIPHOP', 'Hip-Hop'), ('R&B', 'R&B')], max_length=50, null=True),
        ),
    ]
