# Generated by Django 3.0 on 2025-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0005_auto_20250217_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
