# Generated by Django 5.1.6 on 2025-03-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0006_alter_musica_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('capa', models.URLField(max_length=500)),
                ('ano', models.IntegerField()),
                ('visualizacoes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicas', to='spacemusic.album'),
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='spacemusic.artista'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='spacemusic.artista'),
        ),
    ]
