# Generated by Django 5.1.2 on 2025-02-16 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_dispositivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='ultimo_acesso',
            new_name='ultima_data_login',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='nome',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sistema_operacional',
            field=models.CharField(default='antigo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
