# Generated by Django 5.1.6 on 2025-03-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0008_alter_musica_album_alter_musica_artista_delete_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='duracao_album',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='link_album',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='link_artista',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='numero_faixas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='popularidade_artista',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='arquivo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='capa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.IntegerField(blank=True, help_text='Duração em segundos', null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='visualizacoes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
