# Generated by Django 5.1.2 on 2025-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_dispositivo_navegador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='sistema_operacional',
            field=models.CharField(max_length=80),
        ),
    ]
