# Generated by Django 5.1.2 on 2025-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0010_alter_dispositivo_sistema_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='via_app',
            field=models.BooleanField(default=False),
        ),
    ]
