# Generated by Django 3.0 on 2025-02-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_auto_20250217_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('filme', 'Filme'), ('serie', 'Série')], max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conteudos/')),
                ('data_lancamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoVisualizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Conteudo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_visualizacao', to='contas.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Conteudo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='contas.Perfil')),
            ],
            options={
                'unique_together': {('perfil', 'conteudo')},
            },
        ),
        migrations.CreateModel(
            name='ContinueAssistindo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_assistido', models.DurationField()),
                ('ultima_visualizacao', models.DateTimeField(auto_now=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Conteudo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continue_assistindo', to='contas.Perfil')),
            ],
            options={
                'unique_together': {('perfil', 'conteudo')},
            },
        ),
    ]
