# Generated by Django 3.1 on 2025-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemusic', '0014_delete_musicatocadarecentemente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
