# Generated by Django 3.0 on 2025-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0016_auto_20250302_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
