# Generated by Django 3.0 on 2025-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0017_auto_20250303_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_perfis/'),
        ),
    ]
