# Generated by Django 5.1.6 on 2025-03-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0028_musicatocada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicaTocada',
        ),
    ]
